sonar.projectKey=solidjs-app
sonar.projectName=SolidJS App
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9002
sonar.token=squ_7b76b1485232dcac0c0f9ffb936a4f77e86c50c4

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.*,**/coverage/**
sonar.tests=src
sonar.test.inclusions=**/*.test.{js,jsx}

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.file.suffixes=.js,.jsx
sonar.sourceEncoding=UTF-8

# Coverage exclusions
sonar.coverage.exclusions=**/node_modules/**,**/*.test.*,src/index.jsx