sonar.projectKey=solidjs-app
sonar.projectName=SolidJS App
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9002
sonar.token=squ_d61aeb29c801d0e724b94012bcab25e71b852043

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.*,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8